
NAME = do-op
FLAGS = -Wall -Wextra -Werror
SRC = srcs/ft_do_op.c srcs/ft_calculate.c
OBJ = main.o ft_do_op.o
INC = includes

all:
	gcc -o $(NAME) $(SRC) -I $(INC) -L ./$(INC) -lft

clean:
	rm -rf $(NAME)
